name: Bad CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: sudo apt-get install python3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover tests

    - name: Run linter
      run: flake8 calculator

    - name: Deploy to production
      run: echo "Deploying to production..."
